Public Class UsuarioDTO

    Public Property Cuenta As Integer
    Public Property Nombre As String
    Public Property Catastral As String
    Public Property Comunidad As String
    Public Property Domicilio As String
    Public Property Giro As String
    Public Property NumExt As String
    Public Property NumInt As String
    Public Property EstadoPredio As Integer
    Public Property Cp As String
    Public Property Id_Colonia As String
    Public Property Colonia As String
    Public Property Rfc As String
    Public Property Municipio As String
    Public Property FechaAlta As Date
    Public Property Fecha_Baja As Date
    Public Property FechaInst As Date
    Public Property Estado As String
    Public Property TipoUsu As String
    Public Property NodeMedidor As String
    Public Property MarcaMedidor As String
    Public Property DiamMedidor As String
    Public Property Sector As String
    Public Property Ruta As String
    Public Property Telefono As String
    Public Property Descripcion_Cuota As String
    Public Property Descripcion As String
    Public Property NumLec As Double
    Public Property LecturaAct As Double
    Public Property Lote As Integer
    Public Property Manzana As Integer
    Public Property Region As String
    Public Property Id_Comunidad As String
    Public Property Convenio As Boolean
    Public Property Mostrar As Boolean
    Public Property ID_TIPO_USUARIO As String
    Public Property Tarifa As String
    Public Property DeudaAgua As Double
    Public Property DeudaAlcantarillado As Double
    Public Property Otros As Double
    Public Property Recargos As Double
    Public Property AlcaConsumo As Decimal
    Public Property Credito As Double
    Public Property Total As Double
    Public Property CamMed As Boolean
    Public Property DirUbi As Boolean
    Public Property DirFis As Boolean
    Public Property LecturaAnt As Double
    Public Property Requeri As Short
    Public Property Cod_Gir As String
    Public Property DirAu As Boolean
    Public Property Ubicacion As String
    Public Property Direccion As String
    Public Property Alcantarillado As Boolean
    Public Property Saneamiento As Boolean
    Public Property IdCuotaValvulista As Integer
    Public Property NodePeriodo As Integer
    Public Property PeriodoAdeudo As String
    Public Property IVA As Double
    Public Property CuentaAnterior As String
    Public Property Consumo As Double
    Public Property Cedula_Catastral As String
    Public Property IdDescuento As Integer
    Public Property Alta As Date
    Public Property Medido As Short
    Public Property Periodo As String
    Public Property Descuento As String
    Public Property Region_Nombre As String


End Class
